components:
- components:
  - layout_properties: {grid_position: 'AVHUVS,ZTJGQM'}
    name: label_title
    properties: {align: center, background: '#0056D6', bold: false, font: Mozilla Headline, font_size: 22, foreground: 'theme:White', role: null, text: Account Roles}
    type: Label
  - layout_properties: {grid_position: 'ERNVCO,KJWZJH'}
    name: spacer_1_copy_3
    properties: {height: 7}
    type: Spacer
  - layout_properties: {grid_position: 'TASNES,FRVZJK'}
    name: txtRole
    properties: {background: 'theme:White', border: solid, font: Mozilla Headline, font_size: 16, foreground: 'theme:Black', placeholder: Enter Role *}
    type: TextBox
  - layout_properties: {grid_position: 'TASNES,ETHYWP'}
    name: txtDescription
    properties: {background: 'theme:White', border: solid, font: Mozilla Headline, font_size: 16, foreground: 'theme:Black', placeholder: 'Enter Role Description * '}
    type: TextBox
  - event_bindings: {click: btn_AddRole_click}
    layout_properties: {grid_position: 'YGTIAN,JIGEWS'}
    name: btn_AddRole
    properties: {align: full, background: '#0056D6', foreground: 'theme:White', text: ADD ROLE}
    type: Button
  - layout_properties: {grid_position: 'LJVWSX,BSCIIT'}
    name: spacer_1
    properties: {height: 12}
    type: Spacer
  - components:
    - layout_properties: {}
      name: repeating_panel_1
      properties: {border: solid, foreground: 'theme:White', item_template: Roles.RowTemplate16}
      type: RepeatingPanel
    layout_properties: {grid_position: 'YSWHVS,AZKFUU'}
    name: data_grid_1
    properties:
      background: theme:Black
      border: solid
      columns:
      - {data_key: Roles, expand: true, id: JKSDUP, title: Roles}
      - {data_key: Description, expand: true, id: VJQQOR, title: Description}
      foreground: theme:White
      wrap_on: mobile
    type: DataGrid
  - layout_properties: {grid_position: 'PPMOTZ,WKQUEG'}
    name: spacer_1_copy
    properties: {height: 32}
    type: Spacer
  - event_bindings: {click: btn_Close_click}
    layout_properties: {grid_position: 'RFGXQD,ZIKXLO'}
    name: btn_Close
    properties: {align: full, background: '#0056D6', foreground: 'theme:White', text: CLOSE}
    type: Button
  - layout_properties: {grid_position: 'YHEDAA,VSQLRY'}
    name: spacer_1_copy_2
    properties: {height: 32}
    type: Spacer
  layout_properties: {full_width_row: true, grid_position: 'PMMEHW,MUKYFK', row_background: 'theme:Black'}
  name: card_1
  properties: {role: card}
  type: ColumnPanel
container: {type: ColumnPanel}
is_package: true
